version: "3.9"

services:
  db:
    image: mariadb
    volumes:
      - ./mysql_db/:/var/lib/mysql/
      - ./docs:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "29391:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "62022:8000"
    depends_on:
      - db